### ISSUE TITLE
Overflowing add in mc::native::mc_avg in 420/12bit mode

### ISSUE THREAD

**Issue by sdroege** [xiph/rav1e#1311]
Related to https://github.com/xiph/rav1e/issues/1300

Same stream, just a few more frames this time. The first frame encodes fine, the second panics with an overflow.

[test2.y4m.zip](https://github.com/xiph/rav1e/files/3233036/test2.y4m.zip)

```
RUST_BACKTRACE=1 target/debug/rav1e test2.y4m --output test
320x240 @ 30/1 fps
encoded 1 frames, 1.425 fps, 876.33 Kb/s                    thread '<unnamed>' panicked at 'attempt to add with overflow', /home/slomo/Projects/rust/rav1e/src/mc.rs:535:11
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic
             at src/libcore/panicking.rs:49
   9: rav1e::mc::native::mc_avg
             at ./src/mc.rs:535
  10: rav1e::partition::PredictionMode::predict_inter
             at ./src/mc.rs:326
             at ./src/partition.rs:1233
  11: rav1e::encoder::motion_compensate
             at ./src/encoder.rs:0
  12: rav1e::encoder::encode_block_b
             at ./src/encoder.rs:1281
  13: rav1e::rdo::rdo_mode_decision::{{closure}}::{{closure}}
             at ./src/rdo.rs:615
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/iter/traits/iterator.rs:604
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/slice/mod.rs:3150
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/iter/traits/iterator.rs:604
             at ./src/rdo.rs:600
  14: rav1e::rdo::rdo_mode_decision::{{closure}}
             at ./src/rdo.rs:677
  15: rav1e::rdo::rdo_mode_decision
             at ./src/rdo.rs:710
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/iter/traits/iterator.rs:604
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/slice/mod.rs:3150
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/iter/traits/iterator.rs:604
             at ./src/rdo.rs:688
  16: rav1e::rdo::rdo_partition_decision
             at ./src/rdo.rs:1194
  17: rav1e::encoder::encode_partition_topdown
             at ./src/encoder.rs:1797
  18: rav1e::encoder::encode_tile
             at ./src/encoder.rs:2185
  19: rayon::iter::plumbing::Folder::consume_iter
             at ./src/encoder.rs:2008
[...]
```

**Comment by rzumer** [comment]
I am looking into this. It seems to happen in debug/dev mode only.

**Comment by sdroege** [comment]
On 22 July 2019 04:50:34 EEST, "Raphaël Zumer" <notifications@github.com> wrote:
>I am looking into this. It seems to happen in debug/dev mode only.

Arithmetic operations only panic on overflow in debug mode by default. It will happen in release mode too but silently wrap around.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sdroege** [comment]
Thanks!
