### ISSUE TITLE
test_encode_decode::bitrate_dav1d failure

### ISSUE THREAD

**Issue by YaLTeR** [xiph/rav1e#1395]
```
---- test_encode_decode::bitrate_dav1d stdout ----
Encoding 64x80 speed 10 quantizer 172 bit-depth 8
Encoded packet 0
Decoding frame 0
Decoded. -> 0
Retrieving frame
Retrieved.
Retrieving frame
Retrieved.
Encoded packet 1
Decoding frame 1
Decoded. -> 0
Retrieving frame
Retrieved.
thread 'test_encode_decode::bitrate_dav1d' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
 [
     241,
     199,
     176,
     51,
     116,
     186,
<    175,
>    174,
     173,
<    195,
<    237,
>    196,
>    238,
     239,
     180,
     137,
     0,
     158,
     39,
     229,
     142,
     211,
     213,
     87,
     47,
     102,
     113,
     205,
     26,
     88,
     1,
     126,
     113,
     251,
     23,
     32,
     100,
     166,
     179,
     248,
     70,
     53,
     75,
     180,
     148,
     191,
     156,
     42,
     104,
     180,
     217,
     85,
     43,
     111,
     99,
     78,
     126,
     236,
     214,
     39,
     106,
     41,
     228,
     190,
<    156,
>    155,
     239,
     125,
 ]

', src/test_encode_decode/mod.rs:120:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:208
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   7: rav1e::test_encode_decode::compare_plane
   8: rav1e::test_encode_decode::dav1d::compare_pic::{{closure}}
   9: <rav1e::test_encode_decode::dav1d::Dav1dDecoder<T> as rav1e::test_encode_decode::TestDecoder<T>>::decode_packet
  10: rav1e::test_encode_decode::TestDecoder::encode_decode
  11: core::ops::function::FnOnce::call_once
  12: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  14: test::run_test::run_test_inner::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:272
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panic.rs:388
             at src/libtest/lib.rs:1468
```
dav1d: `0.3.1-0-gc9427fd`
rav1e: cb4d396f43316e8739eece66510fb69a07379db1
I tried testing with latest master dav1d but it segfaulted. `bitrate_aom` works fine.

**Comment by lu-zero** [comment]
could you please provide a backtrace of the segfault?

**Comment by YaLTeR** [comment]
Interestingly enough, running the test in debug or in release with `debug = true` doesn't crash latest master dav1d (shows a similar test failure). Running in release gives the following backtrace:
```
#0  0x0000000000000000 in ?? ()
#1  0x00007ff65133e779 in dav1d_log (c=<optimized out>, format=<optimized out>) at ../src/log.c:55
#2  0x00005565556dce20 in ?? ()
#3  0x00007ff650fe2900 in ?? ()
#4  0x00005565556dd701 in ?? ()
#5  0x00005565538fc7df in register_dtor () at src/libstd/sys/unix/fast_thread_local.rs:28
#6  register_dtor<core::cell::RefCell<core::option::Option<alloc::boxed::Box<Write>>>> () at src/libstd/thread/local.rs:386
#7  get<core::cell::RefCell<core::option::Option<alloc::boxed::Box<Write>>>> () at src/libstd/thread/local.rs:377
#8  __getit () at src/libstd/thread/local.rs:185
#9  try_with<core::cell::RefCell<core::option::Option<alloc::boxed::Box<Write>>>,closure,core::option::Option<alloc::boxed::Box<Write>>> () at src/libstd/thread/local.rs:296
#10 0x0000000000000000 in ?? ()
```

**Comment by lu-zero** [comment]
Looks like the dav1d logger is doing something, the off by one failure is something existing since the beginning.

**Comment by tdaede** [comment]
Dumping the ivf, the dav1d and aom md5's match. So I think it's some issue with calling the dav1d api.

**Comment by tdaede** [comment]
Quantizers 159 and below pass, quantizers 160 and above fail. I still can't replicate the failure outside of rav1e.

**Comment by YaLTeR** [comment]
This was apparently fixed somewhere along the way.
