### ISSUE TITLE
assertion failed: units_x + units_cols <= rs_cols + 1 with ChromaSampling::Cs422

### ISSUE THREAD

**Issue by sdroege** [xiph/rav1e#1692]
This is a regression from @xiphmont 's commit 70cb11ff76e553752c9963d974afb3fbc4d3375b some days ago. Before that it worked fine, afterwards not.

The following change to `simple_encoding.rs` shows the assertion

```diff
diff --git a/examples/simple_encoding.rs b/examples/simple_encoding.rs
index d9ba817..f038e06 100644
--- a/examples/simple_encoding.rs
+++ b/examples/simple_encoding.rs
@@ -5,10 +5,11 @@ use rav1e::*;
 fn main() {
   let mut cfg = Config::default();
 
-  cfg.enc.width = 64;
-  cfg.enc.height = 96;
+  cfg.enc.width = 160;
+  cfg.enc.height = 120;
 
   cfg.enc.speed_settings = SpeedSettings::from_preset(9);
+  cfg.enc.chroma_sampling = color::ChromaSampling::Cs422;
 
   let mut ctx: Context<u16> = cfg.new_context().unwrap();
 
```

The width/height change also is relevant, but not sure what the relationship there is.

Fails with

```
Sending frame 0
Sending frame 1
Sending frame 2
Sending frame 3
Sending frame 4
Sending frame 5
Sending frame 6
Sending frame 7
Sending frame 8
Sending frame 9
Sending frame 10
thread 'main' panicked at 'assertion failed: units_x + units_cols <= rs_cols + 1', src/tiling/tile_restoration_state.rs:385:1
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::begin_panic
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:411
   8: rav1e::tiling::tile_restoration_state::TileRestorationStateMut::new
             at ./src/tiling/tile_state.rs:0
   9: rav1e::tiling::tile_state::TileStateMut<T>::new
             at ./src/tiling/tile_state.rs:113
  10: <rav1e::tiling::tiler::TileContextIterMut<T> as core::iter::traits::iterator::Iterator>::next
             at ./src/tiling/tiler.rs:190
  11: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/vec.rs:1883
  12: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/vec.rs:1796
  13: core::iter::traits::iterator::Iterator::collect
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:1466
  14: rav1e::api::internal::ContextInner<T>::compute_lookahead_motion_vectors
             at ./src/api/internal.rs:575
  15: rav1e::api::internal::ContextInner<T>::compute_lookahead_data
             at ./src/api/internal.rs:792
  16: rav1e::api::internal::ContextInner<T>::send_frame
             at ./src/api/internal.rs:292
  17: rav1e::api::Context<T>::send_frame
             at ./src/api/mod.rs:320
  18: simple_encoding::main
             at examples/simple_encoding.rs:22
```

**Comment by xiphmont** [comment]
The specific bisection point appears to be the trigger, not the cause.  Continuing to look.

**Comment by xiphmont** [comment]
Oh, right.  Restoration can't do 4:2:2 at all right now, but the tiling code uses LRU stuff even when restoration isn't active.  I suppose there's no time like the present to implement the needed 4:2:2 support.

**Comment by sdroege** [comment]
Thanks for fixing this so fast! FWIW, this came up from running the testsuite of the GStreamer rav1e plugin. If there's any interest, I could set up something here that runs tests in various configurations via GStreamer. In the past that was quite efficient to find assertions popping up in rav1e :)

**Comment by xiphmont** [comment]
Well, it certainly wouldn't be *un*welcome...
I assume that the tests would be hard to port into the CI framework we have here...

**Comment by sdroege** [comment]
They're actually really trivial tests right now. Just passing some frames in every possible input format through the encoder and making sure it doesn't explode in one way or another. That should be easy to replicate relatively easily. Might be easier than setting up something around GStreamer here.
