### ISSUE TITLE
Various tests failures on i686

### ISSUE THREAD

**Issue by eclipseo** [xiph/rav1e#2124]
With rust 1.40 on Fedora Rawhide on i686 only (armv7hl is fine):

```
failures:
---- api::test::output_frameno_reorder_minus_3 stdout ----
thread 'api::test::output_frameno_reorder_minus_3' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
---- api::test::pyramid_level_reorder_minus_0 stdout ----
thread 'api::test::pyramid_level_reorder_minus_0' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/libcore/result.rs:1165:5
---- api::test::output_frameno_reorder_minus_4 stdout ----
thread 'api::test::output_frameno_reorder_minus_4' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/libcore/result.rs:1165:5
---- api::test::output_frameno_no_scene_change_at_short_flash_2 stdout ----
thread 'api::test::output_frameno_no_scene_change_at_short_flash_2' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/libcore/result.rs:1165:5
---- api::test::output_frameno_reorder_scene_change_at_4 stdout ----
thread 'api::test::output_frameno_reorder_scene_change_at_4' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/libcore/result.rs:1165:5
---- api::test::output_frameno_incremental_reorder_scene_change_at_0 stdout ----
thread 'api::test::output_frameno_incremental_reorder_scene_change_at_0' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/libcore/result.rs:1165:5
---- api::test::output_frameno_incremental_reorder_keyframe_at_2 stdout ----
thread 'api::test::output_frameno_incremental_reorder_keyframe_at_2' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/libcore/result.rs:1165:5
---- api::test::output_frameno_reorder_scene_change_at_2 stdout ----
thread 'api::test::output_frameno_reorder_scene_change_at_2' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/libcore/result.rs:1165:5
---- api::test::output_frameno_no_scene_change_at_multiple_flashes stdout ----
thread 'api::test::output_frameno_no_scene_change_at_multiple_flashes' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/libcore/result.rs:1165:5
---- api::test::output_frameno_no_scene_change_at_short_flash_3 stdout ----
thread 'api::test::output_frameno_no_scene_change_at_short_flash_3' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/libcore/result.rs:1165:5
---- api::test::pyramid_level_reorder_minus_3 stdout ----
thread 'api::test::pyramid_level_reorder_minus_3' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/libcore/result.rs:1165:5
---- api::test::pyramid_level_reorder_minus_4 stdout ----
thread 'api::test::pyramid_level_reorder_minus_4' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/libcore/result.rs:1165:5
---- api::test::pyramid_level_reorder_minus_1 stdout ----
thread 'api::test::pyramid_level_reorder_minus_1' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/libcore/result.rs:1165:5
---- api::test::pyramid_level_reorder_scene_change_at_0 stdout ----
thread 'api::test::pyramid_level_reorder_scene_change_at_0' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/libcore/result.rs:1165:5
---- api::test::pyramid_level_reorder_scene_change_at_3 stdout ----
thread 'api::test::pyramid_level_reorder_scene_change_at_3' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/libcore/result.rs:1165:5
---- api::test::pyramid_level_reorder_minus_2 stdout ----
thread 'api::test::pyramid_level_reorder_minus_2' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/libcore/result.rs:1165:5
---- api::test::pyramid_level_reorder_scene_change_at_1 stdout ----
thread 'api::test::pyramid_level_reorder_scene_change_at_1' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/libcore/result.rs:1165:5
---- api::test::zero_frames stdout ----
thread 'api::test::zero_frames' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/libcore/result.rs:1165:5
failures:
    api::test::output_frameno_incremental_reorder_keyframe_at_2
    api::test::output_frameno_incremental_reorder_scene_change_at_0
    api::test::output_frameno_no_scene_change_at_multiple_flashes
    api::test::output_frameno_no_scene_change_at_short_flash_2
    api::test::output_frameno_no_scene_change_at_short_flash_3
    api::test::output_frameno_reorder_minus_3
    api::test::output_frameno_reorder_minus_4
    api::test::output_frameno_reorder_scene_change_at_2
    api::test::output_frameno_reorder_scene_change_at_4
    api::test::pyramid_level_reorder_minus_0
    api::test::pyramid_level_reorder_minus_1
    api::test::pyramid_level_reorder_minus_2
    api::test::pyramid_level_reorder_minus_3
    api::test::pyramid_level_reorder_minus_4
    api::test::pyramid_level_reorder_scene_change_at_0
    api::test::pyramid_level_reorder_scene_change_at_1
    api::test::pyramid_level_reorder_scene_change_at_3
    api::test::zero_frames
test result: FAILED. 89 passed; 18 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by eclipseo** [comment]
The errors seem intermittent, sometimes the tests are successful. This make it difficult to reproduce.

**Comment by lu-zero** [comment]
Run the tests as `cargo test -- --test-threads=1`, that might workaround the problem.

I will extend the API to reuse a pool and have the tests use the global pool to avoid this.

**Comment by tdaede** [comment]
Does this happen when building locally or only on Fedora CI?

**Comment by eclipseo** [comment]
> Does this happen when building locally or only on Fedora CI?

I can't test locally I don't have access to a i686 system.

> Run the tests as `cargo test -- --test-threads=1`, that might workaround the problem.
> 
> I will extend the API to reuse a pool and have the tests use the global pool to avoid this.

I will try this.

**Comment by dbermond** [comment]
I'm getting similar `thread panicked` error messages for prep_8tap tests on Arch Linux x86_64 after the introduction of these tests by recent commits 8fa818bce51d42d180cf567d51377aa45b7aca6d and cd2aadf4908469ca302de1d335c23bc899f053c2. Like this:
```
---- asm::x86::mc::test::test_rav1e_prep_8tap_regular_smooth_bd_8_avx2 stdout ----
thread 'asm::x86::mc::test::test_rav1e_prep_8tap_regular_smooth_bd_8_avx2' panicked at 'assertion failed: `(left == right)`
```

Adding `-- --test-threads=1` does not solve the issue. The put_8tap tests are passing.

The original issue is for i686, but is this releated in some way?
