### ISSUE TITLE
Building rav1e on Windows missing nasm-rs?

### ISSUE THREAD

**Issue by kevmo314** [xiph/rav1e#2214]
Hi, I get the following error when building `rav1e` on Windows with a `nasm.exe` (2.14.03rc2) on my PATH.

```
> cargo build
...
thread 'main' panicked at 'failed to spawn process: The system cannot find the file specified. (os error 2)', C:\Users\Kevin\.cargo\registry\src\github.com-1ecc6299db9ec823\nasm-rs-0.1.7\src\lib.rs:339:19
```

Is there something else that needs to be done? I also tried adding `nasm-rs` to my dependencies but no luck.

**Comment by kevmo314** [comment]
Ah, I see that I misread the error message, it's actually complaining about a file in the prior command not being found. Here's the line in before it that it's failing on:

```
running: "lib" "/OUT:C:\\Users\\Kevin\\AppData\\Local\\Temp\\cargo-installgxwnk4\\release\\build\\rav1e-fee9995ebf397956\\out\\rav1easm.lib" "C:\\Users\\Kevin\\AppData\\Local\\Temp\\cargo-installgxwnk4\\release\\build\\rav1e-fee9995ebf397956\\out\\src/x86/ipred.o" "C:\\Users\\Kevin\\AppData\\Local\\Temp\\cargo-installgxwnk4\\release\\build\\rav1e-fee9995ebf397956\\out\\src/x86/ipred_ssse3.o" "C:\\Users\\Kevin\\AppData\\Local\\Temp\\cargo-installgxwnk4\\release\\build\\rav1e-fee9995ebf397956\\out\\src/x86/itx.o" "C:\\Users\\Kevin\\AppData\\Local\\Temp\\cargo-installgxwnk4\\release\\build\\rav1e-fee9995ebf397956\\out\\src/x86/itx_ssse3.o" "C:\\Users\\Kevin\\AppData\\Local\\Temp\\cargo-installgxwnk4\\release\\build\\rav1e-fee9995ebf397956\\out\\src/x86/mc.o" "C:\\Users\\Kevin\\AppData\\Local\\Temp\\cargo-installgxwnk4\\release\\build\\rav1e-fee9995ebf397956\\out\\src/x86/mc_ssse3.o" "C:\\Users\\Kevin\\AppData\\Local\\Temp\\cargo-installgxwnk4\\release\\build\\rav1e-fee9995ebf397956\\out\\src/x86/me.o" "C:\\Users\\Kevin\\AppData\\Local\\Temp\\cargo-installgxwnk4\\release\\build\\rav1e-fee9995ebf397956\\out\\src/x86/sad_sse2.o" "C:\\Users\\Kevin\\AppData\\Local\\Temp\\cargo-installgxwnk4\\release\\build\\rav1e-fee9995ebf397956\\out\\src/x86/sad_avx.o" "C:\\Users\\Kevin\\AppData\\Local\\Temp\\cargo-installgxwnk4\\release\\build\\rav1e-fee9995ebf397956\\out\\src/x86/satd.o" "C:\\Users\\Kevin\\AppData\\Local\\Temp\\cargo-installgxwnk4\\release\\build\\rav1e-fee9995ebf397956\\out\\src/x86/cdef.o" "C:\\Users\\Kevin\\AppData\\Local\\Temp\\cargo-installgxwnk4\\release\\build\\rav1e-fee9995ebf397956\\out\\src/x86/tables.o"

--- stderr
thread 'main' panicked at 'failed to spawn process: The system cannot find the file specified. (os error 2)', C:\Users\Kevin\.cargo\registry\src\github.com-1ecc6299db9ec823\nasm-rs-0.1.7\src\lib.rs:339:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Turns out I don't have a `lib.exe` in my PATH, which is installed with the Visual C/C++ toolchain. Mine was under `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\Hostx64\x64`. Adding this to my PATH solved the issue. Perhaps there is a more obvious way to add this binary to the PATH instead of manually, but this works for me for now.
