### ISSUE TITLE
OpenSSL link error installing cargo-c

### ISSUE THREAD

**Issue by dp289m** [xiph/rav1e#2539]
Just downloaded and installed OpenSSL version 1.1.1g (latest stable)
./config && make && make install && export OPENSSL_DIR=/usr/local/

then  rav1e:

```
 **RUST_BACKTRACE=full cargo install cargo-c**
    Updating crates.io index
  Installing cargo-c v0.6.13
  Downloaded serde_derive v1.0.116
  Downloaded serde v1.0.116
  Downloaded 2 crates (125.1 KB) in 0.39s
   Compiling libc v0.2.77
   Compiling cfg-if v0.1.10
   Compiling pkg-config v0.3.18
   Compiling autocfg v1.0.1
   Compiling proc-macro2 v1.0.21
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.40
   Compiling serde_derive v1.0.116
   Compiling version_check v0.9.2
   Compiling serde v1.0.116
   Compiling bitflags v1.2.1
   Compiling getrandom v0.1.15
   Compiling lazy_static v1.4.0
   Compiling log v0.4.11
   Compiling memchr v2.3.3
   Compiling matches v0.1.8
   Compiling tinyvec v0.3.4
   Compiling ryu v1.0.5
   Compiling typenum v1.12.0
   Compiling serde_json v1.0.57
   Compiling unicode-width v0.1.8
   Compiling percent-encoding v2.1.0
   Compiling ppv-lite86 v0.2.9
   Compiling openssl-probe v0.1.2
   Compiling itoa v0.4.6
   Compiling regex-syntax v0.6.18
   Compiling anyhow v1.0.32
   Compiling curl v0.4.33
   Compiling crc32fast v1.2.0
   Compiling foreign-types-shared v0.1.1
   Compiling openssl v0.10.30
   Compiling strsim v0.8.0
   Compiling ansi_term v0.11.0
   Compiling vec_map v0.8.2
   Compiling unicode-segmentation v1.6.0
   Compiling remove_dir_all v0.5.3
   Compiling utf8parse v0.1.1
   Compiling quick-error v1.2.3
   Compiling fnv v1.0.7
   Compiling same-file v1.0.6
   Compiling hex v0.3.2
   Compiling cbindgen v0.14.4
   Compiling semver-parser v0.7.0
   Compiling termcolor v1.1.0
   Compiling humantime v2.0.1
   Compiling hex v0.4.2
   Compiling lazycell v1.3.0
   Compiling rustc-workspace-hack v1.0.0
   Compiling opener v0.4.1
   Compiling glob v0.3.0
   Compiling bytesize v1.0.1
   Compiling home v0.5.3
   Compiling shell-escape v0.1.5
   Compiling unicode-bidi v0.3.4
   Compiling thread_local v1.0.1
   Compiling textwrap v0.11.0
   Compiling unicode-normalization v0.1.13
   Compiling foreign-types v0.3.2
   Compiling vte v0.3.3
   Compiling humantime v1.3.0
   Compiling walkdir v2.3.1
   Compiling heck v0.3.1
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling im-rc v14.3.0
   Compiling crossbeam-utils v0.7.2
   Compiling strip-ansi-escapes v0.1.0
   Compiling aho-corasick v0.7.13
   Compiling bstr v0.2.13
   Compiling quote v1.0.7
   Compiling idna v0.2.0
   Compiling jobserver v0.1.21
   Compiling atty v0.2.14
   Compiling socket2 v0.3.15
   Compiling filetime v0.2.12
   Compiling num_cpus v1.13.0
   Compiling clap v2.33.3
   Compiling cc v1.0.59
   Compiling rand_core v0.5.1
   Compiling tar v0.4.30
   Compiling url v2.1.1
   Compiling bitmaps v2.1.0
   Compiling regex v1.3.9
   Compiling rand_chacha v0.2.2
   Compiling rand_xoshiro v0.4.0
   Compiling rand v0.7.3
   Compiling globset v0.4.5
   Compiling env_logger v0.7.1
   Compiling tempfile v3.1.0
   Compiling ignore v0.4.16
   Compiling sized-chunks v0.5.3
   Compiling openssl-sys v0.9.58
   Compiling libz-sys v1.1.2
   Compiling libnghttp2-sys v0.1.4+1.41.0
   Compiling curl-sys v0.4.36+curl-7.71.1
   Compiling libssh2-sys v0.2.19
   Compiling libgit2-sys v0.12.13+1.0.1
   Compiling flate2 v1.0.17
error: failed to run custom build command for `openssl-sys v0.9.58`

Caused by:
  process didn't exit successfully: `/tmp/cargo-install5I6Cs2/release/build/openssl-sys-e71f7b0d2db9593a/build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR = /usr/local/
  cargo:rustc-link-search=native=/usr/local/lib
  cargo:include=/usr/local/include
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "/usr/local/include" "-Wall" "-Wextra" "-E" "build/expando.c"
  exit code: 0
  cargo:rustc-cfg=osslconf="OPENSSL_NO_SSL3_METHOD"
  cargo:conf=OPENSSL_NO_SSL3_METHOD
  cargo:rustc-cfg=ossl101
  cargo:rustc-cfg=ossl102
  cargo:rustc-cfg=ossl102f
  cargo:rustc-cfg=ossl102h
  cargo:rustc-cfg=ossl110
  cargo:rustc-cfg=ossl110f
  cargo:rustc-cfg=ossl110g
  cargo:rustc-cfg=ossl110h
  cargo:rustc-cfg=ossl111
  cargo:rustc-cfg=ossl111b
  cargo:rustc-cfg=ossl111c
  cargo:version_number=1010107f
  cargo:version=111
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIBS
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIBS unset
  cargo:rerun-if-env-changed=OPENSSL_LIBS
  OPENSSL_LIBS unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_STATIC
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_STATIC unset
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  OPENSSL_STATIC unset

  --- stderr
  thread 'main' panicked at 'OpenSSL libdir at `/usr/local/lib` does not contain the required files to either statically or dynamically link OpenSSL', /usr/local/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.58/build/main.rs:320:13
  stack backtrace:
     0:     0x55eabb4edb55 - backtrace::backtrace::libunwind::trace::h14d338b30b3ea0a7
                                 at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
     1:     0x55eabb4edb55 - backtrace::backtrace::trace_unsynchronized::h73ea91d74a3fd67f
                                 at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
     2:     0x55eabb4edb55 - std::sys_common::backtrace::_print_fmt::hd42948c952866e12
                                 at src/libstd/sys_common/backtrace.rs:78
     3:     0x55eabb4edb55 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha8f928866ff7571e
                                 at src/libstd/sys_common/backtrace.rs:59
     4:     0x55eabb511dcc - core::fmt::write::he0c1e5f7426d2718
                                 at src/libcore/fmt/mod.rs:1076
     5:     0x55eabb4ea612 - std::io::Write::write_fmt::hf3afc6cfd57d0033
                                 at src/libstd/io/mod.rs:1537
     6:     0x55eabb4f0300 - std::sys_common::backtrace::_print::hfc0110703f3696fd
                                 at src/libstd/sys_common/backtrace.rs:62
     7:     0x55eabb4f0300 - std::sys_common::backtrace::print::h3f77c6990ddfaa22
                                 at src/libstd/sys_common/backtrace.rs:49
     8:     0x55eabb4f0300 - std::panicking::default_hook::{{closure}}::heae49580a8d62d75
                                 at src/libstd/panicking.rs:198
     9:     0x55eabb4f004c - std::panicking::default_hook::hecc34e3f729e213c
                                 at src/libstd/panicking.rs:217
    10:     0x55eabb4f0943 - std::panicking::rust_panic_with_hook::he82f5d0644692441
                                 at src/libstd/panicking.rs:526
    11:     0x55eabb4f053b - rust_begin_unwind
                                 at src/libstd/panicking.rs:437
    12:     0x55eabb4f04ab - std::panicking::begin_panic_fmt::h905a6d44880d49ef
                                 at src/libstd/panicking.rs:391
    13:     0x55eabb4b4716 - build_script_main::main::h57b890e48abd1e6f
    14:     0x55eabb4b5ab3 - std::rt::lang_start::{{closure}}::heb9170d56df6a488
    15:     0x55eabb4f0d13 - std::rt::lang_start_internal::{{closure}}::h5d3ea623498f5f43
                                 at src/libstd/rt.rs:52
    16:     0x55eabb4f0d13 - std::panicking::try::do_call::hac65e71be769a440
                                 at src/libstd/panicking.rs:348
    17:     0x55eabb4f0d13 - std::panicking::try::hd4706e264bcf6712
                                 at src/libstd/panicking.rs:325
    18:     0x55eabb4f0d13 - std::panic::catch_unwind::h948a0fb4a8b3ee82
                                 at src/libstd/panic.rs:394
    19:     0x55eabb4f0d13 - std::rt::lang_start_internal::h72cc068ed2d0ac53
                                 at src/libstd/rt.rs:51
    20:     0x55eabb4b5a92 - main
    21:     0x7f46ccc1a02a - __libc_start_main
    22:     0x55eabb4b0d5a - _start
    23:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-c v0.6.13`, intermediate artifacts can be found at `/tmp/cargo-install5I6Cs2`

Caused by:
  build failed

```

**Comment by rzumer** [comment]
This seems like an issue that should be opened at https://github.com/lu-zero/cargo-c.

**Comment by lu-zero** [comment]
From what I'm seeing:
```
  thread 'main' panicked at 'OpenSSL libdir at `/usr/local/lib` does not contain the required files to either statically or dynamically link OpenSSL', /usr/local/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.58/build/main.rs:320:13
```

Pass `--features=cargo/vendored-openssl` and do not try to build a custom openssl on your own.

Check https://github.com/sfackler/rust-openssl for more information if you really want to do on your own.

**Comment by dp289m** [comment]
Thank you lu-zero. 
Custom builds is the name of the game always, don't try to pretend it is not : )

**Comment by lu-zero** [comment]
Hopefully we'll not depend on openssl as TLS provider and that problem would go away... But it is never too soon.
