### ISSUE TITLE
[BUG] CDEF is causing overflow with cargo test in debug mode

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#399]
As of 01ec008aa58192503f4d6a1aee777660cac5bbfe, Aug 1,
"RUST_BACKTRACE=1 cargo test --features=decode_test -- --ignored" gives
all 3 test failures.

The crash point is:  rav1e::cdef::cdef_find_dir at src/cdef.rs:58
```
lassen:rav1e yushin$ RUST_BACKTRACE=1 cargo test --features=decode_test -- --ignored
   Compiling rav1e v0.1.0 (file:///Users/yushin/workspace/rav1e)
    Finished dev [unoptimized + debuginfo] target(s) in 44.28s
     Running target/debug/deps/rav1e-4915d6be767af556

running 3 tests
test test_encode_decode::dimensions ... FAILED
test test_encode_decode::quantizer ... FAILED
test test_encode_decode::speed ... FAILED

failures:

---- test_encode_decode::dimensions stdout ----
	Encoding 8x8 speed 4 quantizer 100
Encoding frame 0
thread 'test_encode_decode::dimensions' panicked at 'attempt to multiply with overflow', src/cdef.rs:58:20
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:463
   5: std::panicking::try::do_call
             at libstd/panicking.rs:350
   6: std::panicking::try::do_call
             at libstd/panicking.rs:328
   7: <&'a T as core::fmt::Display>::fmt
             at libcore/panicking.rs:71
   8: <&'a T as core::fmt::Display>::fmt
             at libcore/panicking.rs:51
   9: rav1e::cdef::cdef_find_dir
             at src/cdef.rs:58
  10: rav1e::cdef::cdef_frame
             at src/cdef.rs:296
  11: rav1e::encode_tile
             at src/lib.rs:1822
  12: rav1e::encode_frame
             at src/lib.rs:1853
  13: rav1e::test_encode_decode::encode_decode
             at src/lib.rs:2157
  14: rav1e::test_encode_decode::dimensions
             at src/lib.rs:2081
  15: rav1e::__test::TESTS::{{closure}}
             at src/lib.rs:2075
  16: core::ops::function::FnOnce::call_once
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
  17: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1451
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
             at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:638
  18: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:105

---- test_encode_decode::quantizer stdout ----
	Encoding 64x80 speed 4 quantizer 80
Encoding frame 0
thread 'test_encode_decode::quantizer' panicked at 'attempt to multiply with overflow', src/cdef.rs:58:20
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:463
   5: std::panicking::try::do_call
             at libstd/panicking.rs:350
   6: std::panicking::try::do_call
             at libstd/panicking.rs:328
   7: <&'a T as core::fmt::Display>::fmt
             at libcore/panicking.rs:71
   8: <&'a T as core::fmt::Display>::fmt
             at libcore/panicking.rs:51
   9: rav1e::cdef::cdef_find_dir
             at src/cdef.rs:58
  10: rav1e::cdef::cdef_frame
             at src/cdef.rs:296
  11: rav1e::encode_tile
             at src/lib.rs:1822
  12: rav1e::encode_frame
             at src/lib.rs:1853
  13: rav1e::test_encode_decode::encode_decode
             at src/lib.rs:2157
  14: rav1e::test_encode_decode::quantizer
             at src/lib.rs:2095
  15: rav1e::__test::TESTS::{{closure}}
             at src/lib.rs:2087
  16: core::ops::function::FnOnce::call_once
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
  17: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1451
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
             at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:638
  18: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:105

---- test_encode_decode::speed stdout ----
	Encoding 64x80 speed 0 quantizer 100
Encoding frame 0
thread 'test_encode_decode::speed' panicked at 'attempt to multiply with overflow', src/cdef.rs:58:20
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:463
   5: std::panicking::try::do_call
             at libstd/panicking.rs:350
   6: std::panicking::try::do_call
             at libstd/panicking.rs:328
   7: <&'a T as core::fmt::Display>::fmt
             at libcore/panicking.rs:71
   8: <&'a T as core::fmt::Display>::fmt
             at libcore/panicking.rs:51
   9: rav1e::cdef::cdef_find_dir
             at src/cdef.rs:58
  10: rav1e::cdef::cdef_frame
             at src/cdef.rs:296
  11: rav1e::encode_tile
             at src/lib.rs:1822
  12: rav1e::encode_frame
             at src/lib.rs:1853
  13: rav1e::test_encode_decode::encode_decode
             at src/lib.rs:2157
  14: rav1e::test_encode_decode::speed
             at src/lib.rs:2064
  15: rav1e::__test::TESTS::{{closure}}
             at src/lib.rs:2056
  16: core::ops::function::FnOnce::call_once
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
  17: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1451
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
             at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:638
  18: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:105


failures:
    test_encode_decode::dimensions
    test_encode_decode::quantizer
    test_encode_decode::speed

test result: FAILED. 0 passed; 3 failed; 0 ignored; 0 measured; 34 filtered out
```

**Comment by tmatth** [comment]
From adding an assertion, it looks like we're squaring 238976 when running those tests, the result of which doesn't fit in 32 bits. 

Not sure where this value is coming from, maybe junk input is being passed into find_dir?

**Comment by ycho** [comment]
@tmatth, hey- thanks for looking at this. I've traced again with assert!(img[i * stride + j] <= 255);
(at line 46, 
for i in 0..8 {
        for j in 0..8 {
               assert!(img[i * stride + j] <= 255);  // <======= HERE!

then found it happens at the rightmost SB block, which straddle on left frame border.
For ex, nyan.y4m, wxh = 480x304, the rightmost SB has 32 pixles only.
Then I see img[i * stride + j]  has 30,000 there.
I will probably PR for adding this assert.

**Comment by xiphmont** [comment]
Ah, I see, and now I understand better what is happening.  Yes, PR the
assert please.

Monty
