### ISSUE TITLE
Encoding with frame reordering segfaults

### ISSUE THREAD

**Issue by SmilingWolf** [xiph/rav1e#720]
Commit 714c5ca7 breaks encoding with frame reordering/"--low_latency false" and makes at least the Win64 build segfault
The build using commit 7862710a is fine
There is no segfault if low_latency is left true

Backtrace:
```
# RUST_BACKTRACE=1 rav1e --limit 390 --low_latency false -o test.limit390.ivf --quantizer 160 -s 3 --tune psnr orig.i420.y4m
1280x720 @ 24000/1001 fps
encoded 1/390 frames, 0.33 fps, 2497.07 Kb/s, est. size: 4.96 MB                    thread 'main' panicked at 'assertion failed: rhs.number == self.number', src\bin\common.rs:149:5
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at libstd\sys\windows\backtrace/mod.rs:104
             at libstd\sys\windows\backtrace/mod.rs:95
   1: std::sys_common::backtrace::print
             at libstd\sys_common/backtrace.rs:71
             at libstd\sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::begin_panic
   6: rav1e::main
   7: std::rt::lang_start::{{closure}}
   8: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
   9: _rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  10: std::panicking::try
             at libstd/panicking.rs:289
  11: std::rt::lang_start_internal
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  12: main
  13: _tmainCRTStartup
  14: mainCRTStartup
  15: unit_addrs_search
  16: unit_addrs_search
```

**Comment by SmilingWolf** [comment]
Commenting out the assert and rebuilding seems to let me encode, but the log looks weirdly numbered:
```
# RUST_BACKTRACE=1 rav1e -v --limit 390 --low_latency false -o test.limit390.ivf --quantizer 160 -s 3 --tune psnr orig.i420.y4m
1280x720 @ 24000/1001 fps
Frame 0 - Key frame - 13331 bytes - encoded 1/390 frames, 0.33 fps, 2497.07 Kb/s, est. size: 4.96 MB
Frame 1 - Inter frame - 492 bytes - encoded 2/390 frames, 0.14 fps, 1294.61 Kb/s, est. size: 2.57 MB
Frame 5 - Inter frame - 6268 bytes - encoded 3/390 frames, 0.10 fps, 1254.43 Kb/s, est. size: 2.49 MB
Frame 9 - Inter frame - 3908 bytes - encoded 4/390 frames, 0.09 fps, 1123.83 Kb/s, est. size: 2.23 MB
Frame 13 - Inter frame - 3691 bytes - encoded 5/390 frames, 0.09 fps, 1037.34 Kb/s, est. size: 2.06 MB
Frame 17 - Inter frame - 5607 bytes - encoded 6/390 frames, 0.08 fps, 1039.49 Kb/s, est. size: 2.06 MB
Frame 21 - Inter frame - 3595 bytes - encoded 7/390 frames, 0.08 fps, 987.19 Kb/s, est. size: 1.96 MB
```
Morevover, the frames' sizes don't match the output of the previous commit (7862710):
```
# RUST_BACKTRACE=1 rav1e --limit 390 --low_latency false -o test.limit390.ivf --quantizer 160 -s 3 --tune psnr orig.i420.y4m
Frame 0 - Key frame - 13331 bytes
Frame 1 - Inter frame - 421 bytes
Frame 2 - Inter frame - 5 bytes
Frame 3 - Inter frame - 61 bytes
Frame 4 - Inter frame - 5 bytes
Frame 5 - Inter frame - 6170 bytes
Frame 6 - Inter frame - 5 bytes
Frame 7 - Inter frame - 88 bytes
Frame 8 - Inter frame - 5 bytes
Frame 9 - Inter frame - 3817 bytes
Frame 10 - Inter frame - 5 bytes
Frame 11 - Inter frame - 81 bytes
Frame 12 - Inter frame - 5 bytes
```

**Comment by shssoichiro** [comment]
I can reproduce this on my end. I'll have a PR out shortly to fix this.
