### ISSUE TITLE
Artifacts in 1280x534 video

### ISSUE THREAD

**Issue by gnafuthegreat** [xiph/rav1e#731]
Using ab4d23e21975f27ad7553081d7e17e16e3c0d794, seeing artifacts in the first 10 seconds of a 1280x534 video.  I've uploaded examples here:

https://themayhaks.com/~gideon/tfe-opening-glitch/

Tested at speeds 3, 4, and 5 (shown in file names), and the artifacts get worse and the faster speeds.  Here's the rav1e line I used (receiving Y4M piped from ffmpeg):

`rav1e --output tfe-10s-rav1e-80-[3,4,5]-kf240.ivf --quantizer 80 --speed [3,4,5] --keyint 240 -`

**Comment by gnafuthegreat** [comment]
Source Y4M (~235MB) here:

https://themayhaks.com/~gideon/tfe-opening-glitch/tfe-10s-opening.y4m

**Comment by rzumer** [comment]
build.sh: `/dev/fd/63 /dev/fd/62 differ: byte 73471551, line 74`

**Comment by rzumer** [comment]
Looks like specific frames are causing issues.

```
$ sed -i '3,70d' tfe-10s-opening.y4m
$ cargo run --bin rav1e --release -- tfe-10s-opening.y4m -o enc_file.y4m -s 3 -l 1 -r rec_file.y4m
    Finished release [optimized] target(s) in 0.06s
     Running `target/release/rav1e broke.y4m -o enc_file.ivf -s 3 -l 1 -r rec_file.y4m`

1280x534 @ 24000/1001 fps
encoded 1/1 frames, 1.00 fps, 68.56 Kb/s, est. size: 0.00 MB                    thread 'main' panicked at 'attempt to divide by zero', src/bin/common.rs:392:14
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: rust_begin_unwind
             at libstd/panicking.rs:326
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::panicking::panic
             at libcore/panicking.rs:52
   9: rav1e::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start
```

With `-l 2`, no crash, but a mismatch on the first frame (using the trimmed file as processed in the command lines above).
