### ISSUE TITLE
Crash when encoding a single frame

### ISSUE THREAD

**Issue by rzumer** [xiph/rav1e#732]
```
$ cargo run --bin rav1e --release -- nyan.y4m -o enc_file.y4m -s 3 -l 1
    Finished release [optimized] target(s) in 0.06s
     Running `target/release/rav1e nyan.y4m -o enc_file.ivf -s 3 -l 1`

1280x534 @ 24000/1001 fps
encoded 1/1 frames, 1.00 fps, 68.56 Kb/s, est. size: 0.00 MB                    thread 'main' panicked at 'attempt to divide by zero', src/bin/common.rs:392:14
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: rust_begin_unwind
             at libstd/panicking.rs:326
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::panicking::panic
             at libcore/panicking.rs:52
   9: rav1e::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start
```

**Comment by tmatth** [comment]
Yup: https://beta.arewecompressedyet.com/?job=rav1e-master%402018-11-14T04%3A01%3A19.904Z
